dist: trusty
language: node_js
sudo: false
node_js:
- '8'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g now
deploy:
  - provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
      branch: master
